services:
  - type: web
    name: lightweight-rdp
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    ports:
      - port: 3389
        protocol: TCP
      - port: 5900
        protocol: TCP
      - port: 10000
        protocol: TCP
    healthCheckPath: /
    autoDeploy: true
