services:
  - type: web
    name: ultra-minimal-rdp-browser
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    startCommand: /bin/sh /app/start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
